### ISSUE TITLE
Cannot read property `forEach` of undefined using `enhance` on TabNavigator

### ISSUE THREAD

**Issue by amsdamsgram** [satya164/react-navigation-addons#4] opened 2017-04-06 05:45 UTC
Hey,

I'm using `enhance` on a `TabNavigator` and I get this error when I start the app.
I get this error in my js console:

```
Warning: Failed prop type: The prop `navigation.state.index` is marked as required in `CardStack`, but its value is `undefined`.
    in CardStack
    in Unknown (created by Navigator)
    in Navigator (created by NavigationContainer)
    in NavigationContainer (created by enhancedScreen(NavigationContainer))
    in enhancedScreen(NavigationContainer) (created by SceneView)
```

Using `react-navigation` v1.0.0-beta7
Any idea of what could do this?

Thanks!

**Comment by JohnCHarrington** [comment] 2017-04-08 10:09
+1 Had this same issue today

**Comment by satya164** [comment] 2017-04-08 11:39
Can you post link to a demo project?

**Comment by shawngustaw** [comment] 2017-04-10 02:31
Can confirm I've also hit this issue.

**Comment by StephenStrickland** [comment] 2017-04-10 05:03
Just added enhance() to a tab navigator and ran into this issue.

**Comment by amsdamsgram** [comment] 2017-04-10 08:41
Hey @satya164,
Here is a repo that reproduce the issue: https://github.com/iDams/react-navigation-addons-issue

It's using RN 0.43.2 with `react-navigation` from `master`. 

Also, I've forked `react-navigation-addons` to fix an issue with RN 0.43.2 as `ReactComponentWithPureRenderMixin` is deprecated now. See my commit to fix it: https://github.com/iDams/react-navigation-addons/commit/68f36b2981c28a5f34b7ae71d7ed3e7cec345221

I might have found what cause the issue doing this repo. It seems like it appears when you enhance a TabNavigator which tabs screens are StackNavigators.
It is working when Tabs screens are just: `{key: 'home', screen: 'HomePage'}` but I get the error when I'm trying to nest a StackNavigator in the TabNavigator.

Hope this will help!

EDIT: Just saw #7 . It is the same issue ;)

**Comment by satya164** [comment] 2017-04-21 18:12
Duplicate of #4

**Closed as completed by satya164** 2017-04-21 18:12 UTC

**Comment by benevbright** [comment] 2017-12-13 11:55
#4 is Duplicate of #4?

**Comment by Donhv** [comment] 2018-01-25 09:59
+1

**Comment by marsonmao** [comment] 2018-03-20 07:34
Not solved yet? :(
